from __future__ import annotations

import argparse
from pathlib import Path
import re
import secrets
import shlex


_ASSIGNMENT = re.compile(r"^(?P<name>[A-Za-z_][A-Za-z0-9_]*)=")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Configure FastAgentFactory for an SSH inference node"
    )
    parser.add_argument("--env-file", type=Path, required=True)
    parser.add_argument("--example-file", type=Path, required=True)
    parser.add_argument("--ssh-host", required=True)
    parser.add_argument("--ssh-port", required=True, type=int)
    parser.add_argument("--ssh-user", required=True)
    parser.add_argument("--ssh-key", default="")
    parser.add_argument("--chat-local-port", required=True, type=int)
    parser.add_argument("--chat-remote-port", required=True, type=int)
    parser.add_argument("--embedding-local-port", required=True, type=int)
    parser.add_argument("--embedding-remote-port", required=True, type=int)
    parser.add_argument("--telemetry-local-port", required=True, type=int)
    parser.add_argument("--telemetry-remote-port", required=True, type=int)
    args = parser.parse_args()

    source = args.env_file if args.env_file.is_file() else args.example_file
    lines = source.read_text(encoding="utf-8").splitlines()
    existing = _values(lines)
    resource_key = existing.get("AGENTFACTORY_RESOURCE_MASTER_KEY") or secrets.token_urlsafe(48)
    updates = {
        "AGENTFACTORY_INFERENCE_RUNTIME_MODE": "external",
        "AGENTFACTORY_LOCAL_INFERENCE_ENDPOINT": f"http://127.0.0.1:{args.chat_local_port}/v1",
        "AGENTFACTORY_LOCAL_EMBEDDING_ENDPOINT": f"http://127.0.0.1:{args.embedding_local_port}",
        "AGENTFACTORY_INFERENCE_TELEMETRY_ENDPOINT": (
            f"http://127.0.0.1:{args.telemetry_local_port}"
        ),
        "AGENTFACTORY_INFERENCE_SSH_HOST": args.ssh_host,
        "AGENTFACTORY_INFERENCE_SSH_PORT": str(args.ssh_port),
        "AGENTFACTORY_INFERENCE_SSH_USER": args.ssh_user,
        "AGENTFACTORY_INFERENCE_SSH_KEY": args.ssh_key,
        "AGENTFACTORY_INFERENCE_SSH_CHAT_LOCAL_PORT": str(args.chat_local_port),
        "AGENTFACTORY_INFERENCE_SSH_CHAT_REMOTE_PORT": str(args.chat_remote_port),
        "AGENTFACTORY_INFERENCE_SSH_EMBEDDING_LOCAL_PORT": str(args.embedding_local_port),
        "AGENTFACTORY_INFERENCE_SSH_EMBEDDING_REMOTE_PORT": str(args.embedding_remote_port),
        "AGENTFACTORY_INFERENCE_SSH_TELEMETRY_LOCAL_PORT": str(args.telemetry_local_port),
        "AGENTFACTORY_INFERENCE_SSH_TELEMETRY_REMOTE_PORT": str(args.telemetry_remote_port),
        "AGENTFACTORY_RESOURCE_MASTER_KEY": resource_key,
    }

    rendered: list[str] = []
    remaining = dict(updates)
    for line in lines:
        match = _ASSIGNMENT.match(line.strip())
        name = match.group("name") if match else ""
        if name in remaining:
            rendered.append(f"{name}={shlex.quote(remaining.pop(name))}")
        else:
            rendered.append(line)
    if remaining:
        rendered.extend(["", "# Generated by deploy.sh"])
        rendered.extend(f"{name}={shlex.quote(value)}" for name, value in remaining.items())

    args.env_file.write_text("\n".join(rendered).rstrip() + "\n", encoding="utf-8")
    args.env_file.chmod(0o600)


def _values(lines: list[str]) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in lines:
        match = _ASSIGNMENT.match(line.strip())
        if not match:
            continue
        name = match.group("name")
        raw = line.split("=", 1)[1].strip()
        if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in {"'", '"'}:
            raw = raw[1:-1]
        values[name] = raw
    return values


if __name__ == "__main__":
    main()
