import Foundation

public let computerUseServerInstructions = """
Computer Use tools let you interact with macOS apps by performing UI actions.

Some apps might have a separate dedicated plugin or skill. You may want to use that plugin or skill instead of Computer Use when it seems like a good fit for the task. While the separate plugin or skill may not expose every feature in the app, if the plugin can perform the task with its available features, prefer it. If the needed capability is not exposed there, use Computer Use may be appropriate for the missing interaction.

Begin by calling `get_app_state` every turn you want to use Computer Use to get the latest state before acting. Codex will automatically stop the session after each assistant turn, so this step is required before interacting with apps in a new assistant turn.

The available tools are list_apps, get_app_state, click, perform_secondary_action, scroll, drag, set_input_target, type_text, press_key, and set_value. If any of these are not available in your environment, use tool_search to surface one before calling any Computer Use action tools.

All actions are bound to the observed window. Window-owned AX actions and an already-confirmed keyboard receiver use directed background delivery. If an application exposes no usable receiver while inactive, the local executor obtains a short foreground focus lease, restores the exact bound input target, performs one keyboard transaction, and restores the previously active application. The model must not use Raise or repeated clicks to prepare keyboard input. Application menu-bar elements outside the observed window are rejected. The clipboard is not used.

After each action, use the action result or fetch the latest state to verify the UI changed as expected.
Every action requires the observation_id printed in the latest state for that app. An action consumes its observation even if it fails. Use the new ID from its result, or call get_app_state again; do not queue multiple actions against an old ID. The CU loop may attach a fresh observation after a failed action; this does not replay the action or make it successful. Use that fresh ID to reassess.
Coordinates are pixels in the returned screenshot. Clicks never select unrelated descendants or activate windows as a fallback. Keyboard actions establish their own receiver as described below.
Use scroll for moving through a page, list, conversation, document, or other content. Target an observed scrollable element when available; otherwise provide x/y inside the intended scroll region and the executor sends a window-targeted wheel event without holding a mouse button. Never use drag to imitate ordinary scrolling. Use drag only when the task explicitly requires holding the primary mouse button to move an object, handle, slider, selection, or other draggable control.
For filling or replacing an entire field, use set_value. Use type_text only when intentionally inserting into and preserving existing text. Do not treat an apparently empty rich-text field as an empty string; its accessible value may contain structural characters. A readback mismatch is not proof that no text was entered. Do not retry, trim or normalize text to manufacture success.

CU binds receiver identity per session, not a copy of the application's text or caret. set_input_target accepts an observed window-owned element_index or explicit x/y in the latest screenshot. If the element exposes no text-selection interface, its current frame is used only as an input-position locator; the binding reports window scope instead of rejecting it based on role. This does not prove editability. Use x/y when the editor exposes no AX node. type_text uses that control's actual selection; press_key can move it. set_value may omit element_index to use the bound target. It selects the full range through the receiver selection API when settable, otherwise sends directed Select All; it verifies the complete range before typing or Backspace for an empty value. For element scope, AXFocused alone is insufficient. A foreground lease reestablishes the same bound element or position locally and aborts if another application takes foreground ownership during delivery. The local executor chooses this mode automatically; do not activate, raise, click, rebind or repeat the text merely because background delivery was unavailable. Loss of receiver identity stops dispatch. Receivers without verifiable full selection reject set_value. Never work around a replacement error with press_key plus type_text; type_text is insertion only and can retain old content. Posted or interrupted input is not permission to replay. Inspect the fresh observation before any further external action.
Prefer element-targeted interactions over coordinate clicks when an index for the targeted element is available. Note that element indices are the sequential integers from the app state's accessibility tree.
Avoid falling back to AppleScript during a computer use session. Prefer Computer Use tools as much as possible to complete tasks.
Ask the user before taking destructive or externally visible actions such as sending, deleting, or purchasing. If helpful, you can ask follow-up questions before taking action to make sure you’re understanding the user’s request correctly.
"""
